name: RAW THOUGHTs
markdown: redcarpet
pygments: true

exclude: ['Rakefile' , '.git', '.gitignore']
keep_files:  ['.git','.svn']

# http://jekyllrb.com/docs/github-pages/#project_pages
baseurl:     /rawthought

